import { API_ROLES, LEGACY_API_ROLES } from './roles';

export const methodRoles: Record<string, string[]> = {
  GET: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR, API_ROLES.VIEWER],
  POST: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR],
  PATCH: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR],
  DELETE: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN],
};
