import { LEGACY_API_ROLES } from './roles';

export const methodRoles: Record<string, string[]> = {
  GET: [LEGACY_API_ROLES.ADMINISTRATOR, 'OPS_USER'],
  POST: [LEGACY_API_ROLES.ADMINISTRATOR, 'OPS_USER'],
  PUT: [LEGACY_API_ROLES.ADMINISTRATOR, 'OPS_USER'],
  PATCH: [LEGACY_API_ROLES.ADMINISTRATOR, 'OPS_USER'],
  DELETE: [LEGACY_API_ROLES.ADMINISTRATOR],
};
