import { API_ROLES, LEGACY_API_ROLES } from './roles';

export const methodRoles: Record<string, string[]> = {
  GET: [
    LEGACY_API_ROLES.ADMINISTRATOR,
    API_ROLES.ADMIN,
    API_ROLES.EDITOR,
    API_ROLES.VIEWER,
    API_ROLES.OPS,
  ],
  POST: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR, API_ROLES.OPS],
  PUT: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR, API_ROLES.OPS],
  PATCH: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN, API_ROLES.EDITOR, API_ROLES.OPS],
  DELETE: [LEGACY_API_ROLES.ADMINISTRATOR, API_ROLES.ADMIN],
};
